In [1]:
import pandas as pd
import numpy as np
import json
import stanza
from sklearn.metrics import classification_report

In [2]:
from utils import Utils

### Load data

In [3]:
!ls dataset

analyze-google-reviews.ipynb			google
analyze-google-topics.ipynb			google-booking-association
booking						google-booking-assoc.json
booking-translate.ipynb				hotel-association.ipynb
collocation-sentence.csv			split-data.ipynb
collocation-sentence-filtered.csv		trip-advisor
create-sent-dataset-for-training-vectors.ipynb	trip-advisor-translate.ipynb
data-analysis.ipynb				word_fixer.py
fix-incorrect-words.ipynb


In [29]:
!ls dataset/google-booking-association

google-booking-association.json  google-booking-hotels-train.json
google-booking-hotels-test.json


In [30]:
google_booking_hotels = Utils.load_json('dataset/google-booking-association/google-booking-association.json')

In [5]:
google_hotel_reviews = Utils.load_json('dataset/google/uk-topic-review-text.json')

In [6]:
booking_hotel_reviews = pd.read_csv('dataset/booking/booking-test.csv')

In [7]:
booking_hotel_reviews.head()

Unnamed: 0                                             title  \
0        1786               Хороше розташування , приємна ціна.   
1        1787                                   в цілому добре.   
2        1788                                   Гарний будинок.   
3        1789  Персонал взагалі не відповідає ніяким критеріям.   
4        1790                                             Все\n   

                                            pos_text  \
0                Хороше розташування , приємна ціна.   
1  Готель хороший, в хорошому місці,гарні номери,...   
2  Гарний будинок. Вид з вікна зачаровує. Затишно...   
3                                                Nan   
4                                                Все   

                                            neg_text  ratingValue  bestRating  \
0  В душі багато павуків, грибок, обідрані дивани...          5.8        10.0   
1  але ліжко двоспальне не передбачає зсунуті два...          7.9        10.0   
2           В душі грибок...Ручка в дверях Коломана.          9.2        10.0   
3  Персонал взагалі не відповідає ніяким критерія...          4.5        10.0   
4                                             Нічого         10.0        10.0   

                          hotel  rating  
0  kiev-hotel-rock-wall.uk.html       3  
1  kiev-hotel-rock-wall.uk.html       4  
2  kiev-hotel-rock-wall.uk.html       5  
3  kiev-hotel-rock-wall.uk.html       2  
4  kiev-hotel-rock-wall.uk.html       5

### Stanza model

In [8]:
nlp = stanza.Pipeline('uk')

2020-06-13 10:21:54 INFO: Loading these models for language: uk (Ukrainian):
| Processor | Package |
-----------------------
| tokenize  | iu      |
| mwt       | iu      |
| pos       | iu      |
| lemma     | iu      |
| depparse  | iu      |

2020-06-13 10:21:54 INFO: Use device: gpu
2020-06-13 10:21:54 INFO: Loading: tokenize
2020-06-13 10:21:56 INFO: Loading: mwt
2020-06-13 10:21:56 INFO: Loading: pos
2020-06-13 10:21:57 INFO: Loading: lemma
2020-06-13 10:21:57 INFO: Loading: depparse
2020-06-13 10:21:58 INFO: Done loading processors!


### Collocation extractor

In [9]:
from collocations.noun_collocation_extractor import NounCollocationExtractor

In [10]:
collocation_extractor = NounCollocationExtractor(nlp)

In [11]:
text_examples = [
    "Чисто, охайно, чай/кава/вода безкоштовна, непогані сніданки і 5 хв до центра міста.",
    "дуже гарний готель, зі смачними сніданками",
    "на сніданок великий вибір страв",
    "Холодна та не свіжа їжа на сніданок",
    "Як на мене ідеальне місце для сніданку.",
    "В готелі є хороший вибір їжі на сніданок.",
    " Їжа смачна, обслуговування на високому рівні.",
    "Дуже приємний сніданок, сервіс найвищого рівня.",
    " В номері було так жарко що довелось відкривати вікна))) сніданки просто супер.",
    
    "Персонал дуже привітний, обслуговування банкету було на вищому рівні",
    "Хороший готель у центральній частині Львова. Чисті та затишні номери, хороші та смачні сніданки. Привітний персонал. Номери достатні по розміру з усім необхідним. Рекомендую для відпочинку."
    
]

In [12]:
collocation_examples = collocation_extractor.extract_for_texts(text_examples)

In [13]:
[Utils.generate_text_from_collocation(collocation_example) for collocation_example in collocation_examples]

['дуже гарний готель',
 'смачними сніданками',
 'на сніданок великий вибір страв',
 'холодна та не свіжа їжа на сніданок',
 'на мене ідеальне місце для сніданку',
 'є хороший вибір їжі на сніданок',
 'їжа смачна',
 'високому рівні',
 'дуже приємний сніданок',
 'відкривати вікна',
 'персонал дуже привітний',
 'обслуговування банкету було',
 'вищому рівні',
 'хороший готель',
 'центральній частині львова',
 'чисті та затишні номери',
 'хороші та смачні сніданки',
 'привітний персонал',
 'номери достатні']

In [14]:
text_example = "В готелі є хороший вибір їжі на сніданок."

In [15]:
doc = nlp(text_example)
doc.sentences[0].print_dependencies()

('В', '2', 'case')
('готелі', '3', 'obl')
('є', '0', 'root')
('хороший', '5', 'amod')
('вибір', '3', 'nsubj')
('їжі', '5', 'nmod')
('на', '8', 'case')
('сніданок', '5', 'nmod')
('.', '3', 'punct')


### FastText model

In [16]:
import fasttext

In [17]:
ft = fasttext.load_model('cc.uk.300.bin')

### Topic classifier 

In [18]:
from topic_classifier import TopicClassifier

In [19]:
topic_classifier_model_file = "models/topic-classifier.sav"

In [20]:
topic_classifier = TopicClassifier(topic_classifier_model_file, ft)

In [21]:
topic_classifier.predict(collocation_examples)[0]

{'Property': [('дуже гарний готель', 1.0),
  ('хороший готель', 1.0),
  ('чисті та затишні номери', 1.0),
  ('номери достатні', 1.0)],
 'Breakfast': [('смачними сніданками', 0.95),
  ('на сніданок великий вибір страв', 0.75),
  ('дуже приємний сніданок', 1.0),
  ('хороші та смачні сніданки', 1.0)],
 'Food and Beverage': [('холодна та не свіжа їжа на сніданок', 1.0),
  ('є хороший вибір їжі на сніданок', 0.95),
  ('їжа смачна', 1.0)],
 'Location': [('на мене ідеальне місце для сніданку', 1.0)],
 'Service': [('високому рівні', 1.0),
  ('персонал дуже привітний', 1.0),
  ('обслуговування банкету було', 0.65),
  ('вищому рівні', 1.0),
  ('привітний персонал', 1.0)],
 'Room amenities': [('відкривати вікна', 1.0)],
 'Atmosphere': [('центральній частині львова', 0.85)]}

### Collocation sentiment classifier

In [22]:
from sentiment_classifier import SentimentClassifier

In [23]:
collocation_sent_classifier = SentimentClassifier('models/sentiment-collocation.json', 
                                                  'models/sent-collocation-word-index.json')

In [24]:
collocation_sent_classifier.predict_sentiments_for_collocations(collocation_examples)

[0.99996793 0.9999827  0.9996362  0.9908552  0.9974269  0.99897385
 0.99996305 1.         1.         0.9999242  1.         0.99992096
 0.99999976 0.9999999  0.9999671  0.9999999  0.9999999  1.
 0.99984014]


['pos',
 'pos',
 'pos',
 'neg',
 'pos',
 'pos',
 'pos',
 'neut',
 'pos',
 'neut',
 'pos',
 'neut',
 'pos',
 'pos',
 'neut',
 'pos',
 'pos',
 'pos',
 'pos']

### Test full pipeline for several hotels

#### Test on google reviews

In [32]:
%%time
google_topic_sent_reports = Utils.calc_classification_report_for_each_topic(hotels = list(google_booking_hotels.keys()), 
                                                                      hotel_reviews=google_hotel_reviews, 
                                                                     collocation_extractor = collocation_extractor,
                                                                     topic_classifier=topic_classifier, 
                                                                     collocation_sent_classifier=collocation_sent_classifier)

[1.         1.         0.9993024  0.999998   0.99999917 0.9999304
 0.99999917 0.9999304  1.         0.9999943  0.9997899  0.9986248
 0.9999999  1.         1.         1.         0.9999982  0.99975735
 0.7155596  1.         1.         0.9999999  0.9952427  1.
 0.99999976 0.99999654 1.         1.         0.9999999  1.
 0.9999248  1.         0.965474   0.9990075  0.99999964 1.
 0.9998895  0.9990802  0.9999995  1.        ]
[0.99999917 0.99999917 0.99999917 0.9999615  0.99999917 0.99999917
 0.9999993  0.99999917 0.99999917 0.9999615  0.80944955 0.9999995
 0.99999917 0.99999917 0.9347416  0.99999917 0.99999917 0.9999988
 0.99999917 0.99978715 0.9999995  0.99999917 1.         0.99999917
 0.9999988  1.         0.9999615  0.9999999  1.         0.99999917
 0.99999917 0.99999917 0.97003156 1.         0.99999607 0.9999999
 0.9998727  0.9999988  0.99999917 0.98492014 1.         0.99999917
 1.        ]
[0.5702129  0.99998295 0.3974136  1.         0.88949865 1.
 0.3974136  1.         1.         0.9999

[0.99999845 0.9998006  0.7826216 ]
[0.9999993 0.9990736 0.9999981 0.999997  0.9991155 1.       ]
[0.99999976]
[0.9999988]
[1.         1.         0.99327636 0.99999654 1.         0.9999987
 0.9998574  0.9999999  0.9999999  0.9768644  1.         0.99988115
 1.         0.9999995  0.9999999  0.99999785 0.9999988  1.
 0.99999964 0.9999994  0.9999999  0.9999956  0.999997   0.9999918
 0.9985973  1.         0.9999949  0.999998   0.9936187  0.9999875
 0.99999106 1.         0.9999994  1.         0.9999335  0.9999825
 0.9703214  0.99964786 0.92889464 0.9999999  1.         1.
 0.9987557  0.9996375  0.99999964 0.9979163  0.9915507  0.99983335
 0.99997354 0.9999373  0.99998474 0.9997782  0.9999294  0.9367596
 0.9999999  1.         0.99999785 0.9999994  1.         0.9979584
 1.         0.99956065 0.99999976 1.         0.9999999  1.
 1.         1.         1.         1.         0.99992466 0.9999999
 0.99945706 0.9999677  1.         0.9999956 ]
[0.99873155 1.         0.99999917 1.         0.8372435  0.9

/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.


[1.         0.99999964 1.         0.9999994  0.99998546 1.
 1.         0.74276453 1.         0.99999845 0.8265645  1.
 0.9999999  1.         0.9999949  1.         0.9999999  0.74985605
 0.999998   0.99979454 1.         1.         0.99978346 0.9999927
 0.99931526 1.         0.9999956  0.99999976 1.         0.99961424
 0.99999976 0.99999905 0.9999157  0.9999882  0.9925338  0.99997234
 0.9999995  1.         0.99999976 0.9996737  0.9999999  0.9993228
 0.99999297 0.99999976 1.         1.         0.9999999  0.9986852
 1.         0.99999774 1.         1.         1.         0.99992704
 0.99690753 0.9999994  0.9995882  0.99999285 0.5412194  0.6157758
 0.99999833 1.         1.         0.99999976 0.9999999 ]
[1.         0.9998807  0.99999917 1.        ]
[0.9999993  0.95650214 1.         0.99999976 1.         1.
 0.9999999  0.9997614  1.         0.9999993  0.99997306 1.
 1.         0.999671   0.99999905 0.9999907  0.9999993  1.
 0.9999981  0.9999968  0.9998337  1.         1.         0.99999475
 0.

[1.         0.999997   1.         0.9999968  0.9997936  0.9999993
 1.         1.         1.         1.         0.99708337 1.
 1.         0.88949865 0.9999994  1.         0.99999976 1.
 0.88949865 0.9999465  1.         0.9999993  0.9984957  1.
 1.         1.         1.         1.         1.         0.9999994
 0.99999976 0.99995995 0.9989504  1.         0.99999976 0.9998461
 0.9999993  1.         1.         1.         0.9189726  0.99890685
 0.78037524 0.9999995  0.9998915  0.999749   0.99999464 1.
 1.         1.         0.9999969  0.6316101  0.3974136  1.
 1.         1.         0.9984915  1.        ]
[1.         0.99999976 1.         0.9973091  0.9999938  0.9999864
 0.9414683  0.99975115 1.         0.99999845 0.99999976 1.
 1.         0.9999988  0.9999757  0.9999658  1.         1.
 0.9999999 ]
[0.9999999  0.53058165 0.99999917 0.9999615  0.99998474 0.9999615
 0.99999917 1.         0.99999917 0.99999917 1.         0.99999917
 1.         0.9999988  0.9949063  0.99999917 0.99999917 0.998891

[0.9999993  1.         0.99698013 1.         1.         0.9999969
 1.         0.99999976 0.9999993  1.         1.         0.9989336
 0.99999    0.99999976 0.9999913  1.        ]
[1.         0.9999025  0.9999989  0.999838   0.99984884 0.99999523
 1.         1.         1.         0.99999857 0.9992798  0.9999999
 0.9999815  0.99999976 0.72133046 0.99999976 0.99999976]
[1.         0.99964845 1.         1.         0.99999976 1.
 1.         0.98663425 1.         1.         1.         0.9999994
 1.         1.        ]
[0.9999721  0.99989283 0.99999535 0.99998486]
[0.99891925 0.99999976]
[0.9993475 0.9999994]
[1.]
[0.9999999  0.9999925  0.9999995  0.9998078  1.         0.99997663
 0.99999976 1.         1.         1.         1.         0.99073327
 0.99317545 0.9999914  1.         0.9999927  0.94318384 0.9999999
 0.99970883 1.         0.95171314 0.99999964 0.9999877  1.
 0.99999905 1.         1.         1.         0.99999964 0.95050085
 0.9999995 ]
[0.99264014 0.9999999  0.77734375 0.67142725 0.

[0.9999938  0.99999964 0.9962018  1.         1.         1.
 1.         0.9999994  0.99664706 1.         0.99985445 1.
 1.         0.99998534 1.         1.         1.         0.99999714]
[0.99999094 0.9999925  0.9999999  0.99999726 0.9999598  0.99999166
 0.9999881  0.9993795  0.99995685]
[0.9999995  0.9999999  0.43387362 1.         1.        ]
[0.99882704]
[0.99726945 0.9999571  0.9999974  0.9999987 ]
[0.996931   0.99965024 0.9999651  0.9997099  0.99999976 1.        ]
[0.5672007  1.         0.9999993  1.         0.9998423  0.9999999
 0.9993223  1.         1.         1.         1.         1.
 0.99999833 0.9999993  0.9999999  0.99984336 0.999894   1.
 0.99999905 1.         0.9999994  0.99988794 0.9995764  0.9999994
 0.99999976 0.99999905 1.         0.99999905 0.9998603  1.
 0.9992712  1.         0.9999037  1.         0.9999883  0.9997662
 0.9990287  0.99915004 0.99999774 0.9999999  0.99999976 0.9999937
 0.7308727  0.99999905 1.         0.99937564 1.         0.9983713
 0.9999037  0.9999999

[0.9999994  1.         0.9999857  1.         1.         0.9999974
 1.         0.99999726 0.9998474  0.99991536 1.         0.9999863 ]
[0.9999999 1.        0.9999622 0.9992823 0.9999461]
[0.9896471 0.9998006 0.9998006]
[0.9997893  0.9999895  0.9994518  0.98994195 0.95937914 0.9945785 ]
[0.9998802  0.99997556]
[0.7926026]
[1.         0.9999999  1.         1.         0.9999995  0.9999982
 1.         1.         1.         1.         1.         0.99999905
 1.         1.         0.9995291  0.9999999  0.9999999  0.9999995
 0.99996793 0.9999932  0.99999666 1.         0.99583423 0.99999785
 0.9999999  1.         0.9999999  0.99999833 0.9903121  0.9999994
 0.9999999  0.99983394 0.99999654 0.9999999  0.99991596 0.9993709
 0.99999917 0.9997595  0.99998856 0.9997595  0.99999845 0.9999995
 0.49203575 0.9377903  0.9999999  1.         0.99999785 0.9999957
 1.         0.99997354 0.9999871  0.9999999  0.99974555 0.9999999
 0.9731617  1.         1.         0.9999434  1.         0.9999995
 0.99972373 0.99

[0.99996567 0.9999999  0.9999205  0.99994755 1.         1.        ]
[0.9998462  0.9999765  0.9998167  1.         0.9999994  1.
 0.9989623  1.         1.         1.         1.         1.
 0.9999994  0.9999999  0.99994016 0.99999976 1.        ]
[0.68053246]
[0.9999685  0.9999982  0.9999449  0.43387362 1.         0.99999964]
[0.9999795 0.999997  1.       ]
[0.9993832  0.94016486]
[0.9999993  0.99999523 0.99885607 1.         0.99999976 0.99999976
 1.         0.9999976  1.         0.88949865 0.9999993  0.9999999
 1.         0.9999982  0.9999993  0.9999995  0.9999902  0.9999999
 1.         1.         1.         0.99993837]
[1.]
[0.9999181]
[0.999845   0.99997926]
[0.9999838]
[0.9998559]
[1.         0.99999917 0.70382184 0.9999999  0.9996855  0.99997663
 0.99177366 0.99999964 0.99979395 1.         0.9964882  1.
 0.50493056 0.9999958  1.         0.9998116  1.         0.9999999
 0.50493056 1.         1.         0.99999976 0.9941316  0.9958081
 0.9998134 ]
[1.         0.99999905 1.         0.999

[1.        1.        0.9999987 1.        1.        1.        1.
 1.        1.        0.9999999 1.        0.9999988 1.        0.9999845
 0.9451881 1.        1.        0.9999999 0.9999989 0.9999975]
[0.9993223  0.99997234 0.99922514 0.9999789  0.9999927  0.9993223
 0.99997234 0.9993223  1.         0.9999994  0.9998462  0.99999595
 0.99992347 0.99997354 0.999998   0.9999994  0.99913836 1.
 0.99999464 0.99999857 1.         0.99999976 0.6688505  0.49203575
 0.99999976 0.99997866]
[0.9999988 1.       ]
[0.9999988 0.9999863]
[0.9999883  0.99999046 0.43387362]
[0.9999703]
[0.99999166]
[0.9999999]
[0.99987316]
[1.         0.9901446  1.         1.         0.9999994  0.88949853
 1.         1.         1.         0.98937863]
[0.9996749  0.9999976  1.         1.         1.         1.
 0.99997544 0.9999994  1.         1.         1.         0.9999993
 0.99999976 1.        ]
[1. 1.]
[0.9868029 1.       ]
[0.99993503]
[0.9999976  1.         0.99999905 1.        ]
[0.9995578  0.99999964 0.9999994 ]
[1.]


[0.9999987  1.         1.         0.90564203 0.87023014 1.
 1.         0.99990916 0.99999976 0.9989434  1.         0.9999294
 0.9999999  0.9171969  1.         0.99999976 0.99976784 1.        ]
[0.99999976 1.         0.59905934 1.         1.         0.9999131
 0.99998176 0.9999988 ]
[0.9999747  1.         0.7038484  1.         1.         1.
 0.8298462  0.9999943  0.99987435 1.         1.         0.99999726
 0.99054986 0.99974865 1.         1.         0.9999058  0.98736304
 0.99918765]
[0.9993438  0.9999999  0.9999999  0.9999827  1.         1.
 0.8946725  0.99996793 0.9999999  1.         0.99999833 1.
 1.         0.99949443 0.99999976 0.98802453 0.99999464 0.9999999
 0.99999976]
[1.         0.99376476]
[1.]
[1.         0.99998975 0.43387362 0.99993193]
[0.9984927]
[0.9999974  0.99987674]
[1.         0.99999917 0.9996805  0.99999654 0.99996495 1.
 1.         0.9999888  0.9980482  1.         0.99999964 1.
 1.         1.         1.         1.         0.99987435 1.
 0.9993024  0.9531292  0.9

[0.9999974]
[0.9999993  0.9996166  0.5300377  1.         1.         1.
 0.999998   1.         1.         0.99999976 0.99999976 1.
 0.9999993  0.99922824 1.         0.99999833 0.99994695 0.9999845
 0.99999964 0.9999993  0.99919504 0.9999995  0.9986047  0.999984
 0.99993384]
[0.9998325  1.         0.9999968  0.99906427 0.99938667 0.7152509
 1.         1.         0.65946966 0.9999893  0.9999999  0.9999747
 0.9998487  1.         0.9999937  0.99973565 0.9999999  0.99994457
 0.82449895 0.98211426 0.99886215 0.9995142  1.         1.
 0.99999964 0.9999981  0.99993217 0.9999999  1.         1.
 0.9999913  0.99978405 1.         0.96786624 1.         0.9999932
 1.        ]
[0.9999926  0.9999999  1.         0.99999964]
[1.         1.         0.99959475 1.         1.         0.9998671
 1.         0.99999774 1.         0.99792284 1.         1.
 1.         1.         0.9999403  1.         0.9997379  1.
 1.        ]
[0.9997788]
[0.99999416 1.         0.99902546 1.         0.9999987 ]
[0.9999782]
[0.995

[1.         0.9999924  1.         0.99998903 0.99999964 0.9999887
 0.7523986  1.         0.99999785 0.99998677 0.99939024 0.99988055
 0.9999988  1.         0.9999918  0.98415726 0.99999094 1.
 0.9999914  0.9998721  0.9993223  1.         0.9989962  0.9999995
 1.         0.9999999  0.9999236  0.999992   0.9999981  1.
 0.999265   0.9999999  0.9995332  0.99999964 0.99993134 1.        ]
[0.99994075 0.9999479  0.9999999 ]
[0.9999993  0.9999943  1.         0.9999994  1.         1.
 1.         0.55011594 0.9999994  0.9999995  0.99611217 0.9999993
 0.9999993  0.88949865 0.9999999  0.9999968  0.9986494  0.9999993
 1.         0.9999999  0.9999999  0.9999993  1.        ]
[1.         0.79992956 0.97552466 1.        ]
[0.9996215  0.99830186 1.         0.82673246 0.93582696]
[0.9999858  0.99999106 1.         0.9968311  0.9993024  1.
 1.         1.         1.         0.99994135 0.99999917 1.
 0.9996691  0.9970989  1.         0.9999907  1.         1.
 0.991122  ]
[0.99999976 0.8396035  0.998953  ]
[0.9

[1.         0.99999976 0.9999999  0.99552494 0.96699774 0.99999785
 0.99999464 1.         0.99997234 1.         0.999645   1.
 0.9999999  0.9999988  0.99988365 0.99994147 0.99999917 0.9999988
 0.9998062  1.         1.         0.9999994  0.99999976 1.
 1.         0.9995003  0.99999976 0.99999785 1.         0.99997354
 1.         1.         0.99999905]
[1.         0.99988985 0.9999993  0.9999999  0.9998807  1.
 1.         0.88949865 0.9999995  0.99111676 0.9999256  0.99999976
 0.99999905 0.9999739  1.         0.99997175 1.         1.
 0.9706988  1.         1.        ]
[0.99891925]
[0.9999987]
[0.99944264 0.9996136  0.9999993  0.9999912  0.999954   0.89827853]
[0.99999964]
[0.9668938 1.        0.9999993 0.9999987 1.        1.        1.       ]
[1.         0.99975497 0.5904504 ]
[0.9631153 0.9999795 0.9999982]
[1.]
[1.         0.99759775 0.9791946  0.99980515 0.9999988  1.
 1.        ]
[1.]
[0.99999666]
[0.9999895]
[1.        0.99999   0.9999962]
[0.99999964]
[1.]
[0.99997795 0.99981624]
[

[1.       1.       1.       0.999997 1.      ]
[0.99999106 0.91048187]
[1.         0.9966678  0.82449895 0.9999995  1.         1.        ]
[0.999997]
[0.999788   0.9997029  0.99996364]
[0.9999895 0.9999982]
[0.99980694 0.9954081  0.99999654 0.99998724 0.9999913  0.9999722
 0.9999833  0.99999774 0.9999999  0.9999927  1.        ]
[1.         1.         0.9999993  0.99573094 0.9999987  0.9999776
 1.        ]
[0.9985482]
[0.99999726]
[0.99947816 0.99999475 0.9999703  0.99891925 0.9999999  0.99999845
 1.         0.8629233 ]
[0.9999943  0.99999976 0.9999851  0.99848926 1.         0.99983394
 0.99997234 0.999998   0.9999927  0.9999833  0.9999622  0.99999976
 1.         0.7820746  0.9999999  1.         0.9999989  1.
 1.         0.9202922  1.         0.9999994  0.9993223  0.9999988
 1.         0.9998945  0.9999994  1.         0.99972373 0.9999815
 0.99905807 0.9999982 ]
[1.         1.         0.9677335  1.         0.99999964 1.
 0.99999917 1.         1.         0.86583555 0.9998073  1.
 1.     

[0.99999976 0.99891925 0.99999964]
[0.9995751  1.         0.99998975 0.9999201  0.99987817 0.99999654
 0.9985642  0.9999852  1.         0.9999683  0.99996936 0.80389845]
[1.        1.        0.9996389]
[0.9963536]
[0.9999927  0.99999547 0.9999999  0.9999995  0.9956589 ]
[0.9999114 0.9998822 0.9999993]
[0.9999932  0.99998033 0.9999566 ]
[0.997644   1.         0.99999845]
[0.99969697]
[0.99999964]
[1.         0.9993223  0.9999924  0.99999654 0.99999964 0.9999999
 0.999998   0.9999974  0.9998529  0.9985973  0.9999968  0.99999964
 0.99966717 1.         0.9992816  0.9876381  0.99997866 0.99999976
 1.         0.9993223  1.         0.9999999  0.99992704 0.9999999
 0.9890049  0.99999976 0.9999956  0.9999999  0.99999976 1.
 1.         0.99997354 0.9988255  0.9998529  0.97645265 0.9999957
 0.99993277 0.99998236 0.9991586 ]
[0.9999896  1.         0.99998844 1.         1.         1.
 0.99999964 0.99835855 0.9999994  0.99998736 1.         1.
 0.9999995  0.99988985 0.88949865 0.99999344 1.         0

[0.9972397  1.         0.99989283 0.99999833 0.99997175 0.99995816
 0.9999995  1.         1.         0.97363764 0.9989102  0.98839486
 1.         0.9999987 ]
[0.99984264]
[0.98750895 0.9999515  0.9999999  0.9999515 ]
[0.9999999  0.99962044 0.8681901  0.9750518 ]
[0.99987316 0.9999999  0.99753296 0.9999999  0.99555826]
[0.99667406 1.        ]
[0.99979764]
[1.         0.9999701  0.9999968  0.99996567 0.99997866 1.
 1.         0.9959598 ]
[1.         0.99999976 0.9962747 ]
[1. 1.]
[0.9999999]
[0.9999012]
[1.]
[0.99996996 0.9999018  0.99521047 0.99999416 0.84534204 0.99994826
 0.9999287  0.9999938  0.6035718  1.         1.         1.
 1.         0.9999713 ]
[0.9999995  0.9999999  1.         0.99998534 1.         1.
 1.         1.         0.9745773  0.9992275  0.6349124  0.9999994 ]
[0.999998   0.99999964 1.         0.9999765  0.9989575  0.9999962
 0.9999722  1.         0.9999999  0.99998474 0.99999654 1.
 0.99997354 1.         0.99979824 0.99703276 0.9999975  0.99999774]
[0.99999964 0.9999

[1.         1.         0.99999774]
[1.        0.9999999 0.9999573 0.9799033 1.        1.        0.9997652
 0.9967528]
[1.         0.9999931  0.99997354 0.99999535]
[1.         0.99998295 0.9999995 ]
[0.9699634]
[0.9924981  1.         0.99999964]
[0.6416195 1.       ]
[1.         0.99999917 0.6380592  0.9999999  0.9997639  1.
 0.9461208  1.         0.9999944  0.9999858  0.9998104  0.99996376
 0.99999964 0.9999969  0.8186837 ]
[0.9999845]
[0.99999654 1.        ]
[0.9999937 1.        1.        1.        0.9999914]
[1.]
[1.         0.9999689  0.99999726 0.9991037 ]
[0.99998057]
[0.80868864]
[1.        1.        0.9329126 1.        0.9999995 0.9962077 0.9875628]
[1.         0.9999993  0.99999976 0.9968214  1.         0.9999988
 0.99999976 0.99999976 0.9999919  0.999995  ]
[1.         0.99999654 0.9999999  1.         0.99999905 0.99999475
 0.99999964 1.         1.         0.99999654 1.         0.99999094
 0.5923292  1.         0.5246802  0.99999917]
[0.9998679  0.99999225]
[0.98318946 0.9999

[1.         0.99684227 0.99999964 0.99942625]
[0.99999774 1.         1.         1.        ]
[0.9999995  1.         1.         1.         1.         0.9999585
 1.         1.         0.9994142  1.         0.99999857 0.9999999
 0.9917532  0.62613   ]
[0.999998  0.9565706 1.        0.9999863 1.       ]
[1.         0.9999999  0.9999994  0.9999995  0.9999993  0.9999999
 1.         0.99992585 1.         0.88949853 0.91179746 0.99986494
 1.         0.86729604 0.99742126]
[1.         0.99713683 0.99953747 1.         0.9999989  0.894807
 0.8833597  0.99999785 0.9999559  0.999998   0.99986815 0.9999999
 1.         1.         1.         0.98563486 1.         1.
 0.99765706 0.99972373 1.         0.99999905 0.912812  ]
[0.99999976 0.99999964 0.9999982  1.         1.         0.999987  ]
[0.9999999]
[0.9999999]
[0.99994004]
[0.9999995  1.         0.99999964 0.9999999  1.        ]
[0.8275521  0.99999845 1.         1.        ]
[0.99830186 0.9999994 ]
[1.]
[0.9999964]
[1.]
[0.99999976]
[1.         1.    

[1.         1.         0.99999976 0.9993962  0.99999857 0.9999927
 0.9999889  0.99988604 1.         1.         0.9999993  0.83149165
 0.99908006 1.         0.9999956  0.9998809  1.         0.9999989 ]
[0.99999964 0.99999976 0.91403997 1.         0.9999995  0.99999964
 0.99999464 1.         1.         1.         1.         0.9999999
 0.99999964 0.999684  ]
[0.99998975 0.99938023 1.         1.         1.         0.9999616 ]
[1.]
[1.]
[0.9972274]
[0.99043953]
[0.80740356]
[0.9999995  0.9996375  1.         0.99999976 0.99999857 0.99999976
 1.         0.99998975]
[1.         0.99842286 0.99977165 0.9994904  0.9999993  1.        ]
[0.9998896]
[0.9998796  0.99999785 0.9986652 ]
[1.         0.99999917 0.9998248  0.99999607 1.        ]
[0.99836284]
[0.99999976]
[0.9999976]
[1.        0.9971017 1.       ]
[0.99999785 0.99999964 0.99906236 0.9999747  1.         1.
 0.99999774 0.9999864  1.         1.         0.99998367]
[0.9999995 0.9999995 0.9999962 1.        1.        1.        0.9999999]
[1.]


[0.999938]
[1.        0.9999995 0.7717559]
[0.9999788]
[0.99999976 0.99997807 0.999894   1.         0.99999654 1.
 0.9999999  0.9853178  0.9999169  0.9999821  0.9999989  1.
 0.9999478  0.9999999  0.9999995  0.99999964 0.9999999  0.9999995
 1.         0.9999999  0.9999956  0.9999776  0.9999999  0.9999641
 0.9999969  0.918643   0.99997485 1.         0.99973804 0.99999726
 1.         1.         0.9999999  0.99999654 0.9999999  0.9999999
 1.         0.998944   1.         0.9997348  1.         0.9999962
 1.         0.9999937  0.99999654 0.9999471  0.4999101  0.9996375
 0.9999999  1.         0.9999994  1.         0.7694475  1.
 0.99998164]
[1.         0.99983513 1.         0.9999994  0.9999993  0.9999993
 0.99820006 1.         0.99999964 1.         0.99999785 0.9999995
 0.9999993  0.9999689  1.         0.99997497 0.9421905  0.9999862
 1.         1.         1.         0.9899573  0.99999964 0.99999213
 0.9999995  0.99840194 0.9999981 ]
[1.]
[0.99307007]
[1.         0.99999964 0.99999976 0.9999

[0.9999989  1.         1.         0.9999994  1.         0.9999999
 0.99999917 1.         0.9978454  1.         0.5904504  0.99999213
 1.         0.99961996 0.99999547 0.99999785 0.9999999  0.9999864
 1.         1.         1.         0.56789166 1.         1.
 1.         0.9999937  0.9993419  0.9999999  0.9999945  1.
 1.         0.5099837  1.         0.99480826 0.999889   0.99999654
 0.96529716 0.99999964 0.9999999  0.99952114 1.         0.9999956
 0.99999964 1.         1.         1.         1.         1.
 0.9996081  1.         1.         0.7633933  0.99994147 0.99998105
 0.9999771  1.         0.9990834  1.         0.9999703  0.9999902
 0.98250985 1.         0.99983335 1.         1.         0.99997354
 1.         1.         0.9999999  0.99999654 0.99998784 0.9999982
 0.9999976  1.         0.9999999  1.         0.9999821  0.999997
 1.         0.9999999  0.9999994  0.99990606 0.98313475 0.77716565
 0.9999999  0.99559826 0.9999993 ]
[0.99999917 0.99999976 0.74264544 1.         1.         1.

[0.99999905 1.         0.99699914 0.9999889  0.99999106 0.99999356
 0.9847199  0.9992731  1.         0.9999975  1.        ]
[0.9999999  0.93935233 0.9711664  0.9999449  0.44560853]
[0.999995   0.99999607 0.99999654 0.9997981  0.99999976 0.99999905
 0.99999976 1.         0.99999964 1.         0.9999993  0.9999573
 1.         0.9999994  1.         0.86729604 0.9999809  1.
 0.9998609  1.         0.9916258  1.         0.9972766  0.9999993
 0.9999993  1.         0.99999976 0.9999999  1.         0.99999607
 0.9995197  0.8702301  0.9999995  0.9999999  1.         0.9999993
 1.         1.         1.         0.9998605  1.         0.88949865
 0.99999917 1.         1.         0.99996436 0.9999989  1.
 1.         0.9995377  1.         0.9999349  0.9999838 ]
[0.9999963  0.9855958  1.         0.5220016  0.99989283]
[0.9999981  0.9999219  0.99999917 0.95312905 1.         0.582311
 0.9999895  1.         0.9999964  0.99999976 1.         1.
 0.9466287  0.99991524 1.         0.99987817 0.95312905 0.999999

[1.]
[0.9999999]
[0.99999964]
[0.999795   1.         1.         0.9999949  1.         1.
 0.9999999  0.9995253  0.99973804 0.99999785 0.99999154 1.
 0.880177   0.9999956  0.9999858  1.         1.         0.9999956
 0.9999988  0.9999995  1.         0.9999988  0.9999987  1.
 1.         0.99999976 0.994669   0.9999821  0.9999999  0.99999213
 0.9999995  1.         1.         0.9999546  0.5923292  0.99208754
 1.         0.9999999 ]
[1.         0.9999994  0.99999976 1.         0.9999949  1.
 0.99999774]
[0.99999845 0.9998029  0.9999678  0.99999845 1.         0.99999905
 1.         1.         0.9999962  0.99999845 0.99999917 1.
 0.99999964]
[1.         0.99974984 0.9979923  0.9999957  1.         0.9998419 ]
[0.88949865 1.         0.9999988  0.99999964 1.         0.9997999
 1.         1.         0.9999995  1.         0.9971335  1.
 1.         1.         0.99999976 0.99999964 1.         0.99999976
 0.6465638  0.9999963  0.9999988  0.9999999  1.         1.
 0.999998  ]
[0.9999999  1.         0.9

[1.]
[1.]
[0.9998839  0.9999937  0.9999987  0.9985495  1.         0.9985257
 0.9999999  0.99940336 1.         0.9996815  0.99987257 1.
 0.99818003 0.99999964 1.         0.995475   0.9999938  0.9214038
 1.         0.99999535 0.9999999  1.         1.         1.
 1.         0.99999094 0.99983335 0.9711032  0.9999999  0.9999995
 0.99941075 0.9996     0.99541676 0.9999877  1.         0.9998423
 0.9999994  0.9999976  0.9998443  1.         1.         1.
 0.97735184 0.93322515 0.9999988  0.95217115 0.99953103 0.99512875
 0.851836   1.         0.9999999  0.99999964 0.9999871  0.99999404
 0.9999858  0.9999988  1.         0.99999833 0.9999821  0.9999943
 0.9998574  0.9291354  1.         0.9999988  1.         0.5061217
 0.99999964 0.99996805 0.5579554  0.9999982  0.9999989  0.9998423
 0.99999976 0.9991586  1.         0.9999993  1.         1.
 1.         0.99999905 0.9999583  0.99999774 0.99999964 0.99997354
 0.999923   0.9997162  0.9997631  0.9999999  0.9999994  0.99999654
 0.9998253  0.99990964 0

[0.99468553 1.        ]
[0.99992526 0.99999964 1.         0.99999    0.99962723 0.9999999
 0.99999046 0.99999654 0.9998634  0.98249924 0.99999976 1.
 0.9998337  1.         0.99999964 0.9999999  0.9825623  1.
 0.9999747 ]
[0.9901978  0.9851751  0.99999297]
[0.9999999  0.9999999  1.         0.9994142  1.         0.9980427
 0.9994142  1.         1.         0.9999304  0.9999999  0.9424914
 0.99970204]
[0.9983279 0.9999995 1.        0.9999807]
[1.]
[1. 1. 1. 1.]
[0.99994206]
[0.9994949]
[0.99998844]
[1.         0.99999905 0.9999999  0.99999905 1.         0.99999964
 0.99999833 1.         0.49203557 0.9999999 ]
[0.9999988  0.99999917]
[0.9999994]
[0.99999785]
[1.         0.9999999  0.9953076  1.         1.         0.99953926
 1.         0.99904794 0.9999999 ]
[1.         0.99956757 0.9999938 ]
[0.99999976]
[1.]
[0.9993057 1.       ]
[1. 1.]
[0.43387365]
[0.9998559]
[0.9999982  0.99308664 0.7687581  1.         0.9994142  1.
 0.99999213 0.9999304  0.9930743  1.         0.99999774 1.
 0.956071 

[1.         0.99742424 0.99998975 0.9999995  0.9999995  0.9999019
 0.9997893 ]
[0.9999995  0.99997973 0.9999807  0.9993488  0.99998784]
[0.9973864]
[0.9989237]
[0.99966836]
[0.99989283 1.         0.999997   0.6241404  0.9995203  1.
 0.99989283 0.99927276 0.9999795  0.99997175 0.99999416 0.9999999
 1.         0.9999645  0.9999931 ]
[0.9999511  0.99999917 0.9999988  0.9999232  0.99999976 0.99999917
 0.99999917 0.9999988  0.99999917 1.         0.98842597 1.
 0.9999999  0.9999651  0.9856067 ]
[1.         1.         1.         0.99998295 0.88949865 0.9992235
 0.9999995  1.         1.         0.9994993  1.         1.
 1.         1.         0.99999905 0.9999993  0.99999964 0.9999999
 0.9999993  0.9916391  0.99999976 0.9992933  1.         1.
 0.9998882  0.88949865 0.99999964 0.99992466 0.9999913  0.99999905
 0.8184604  0.9693085  1.         1.         0.9629743  1.
 1.         0.9999999  1.         1.         1.         1.
 1.         0.99023    1.         1.         0.99999976 0.9999949
 0.99

[0.99999964 0.9999964  0.9609139  0.99999774]
[0.9998448 0.5049306 1.        0.9998634]
[0.74993753]
[0.9999999  0.998223   0.9999769  0.81258464 1.         1.
 1.        ]
[0.99998343 0.9999865  1.         1.         1.         1.
 0.71151847 1.        ]
[1.]
[0.99700314 0.9999924  1.        ]
[1.         1.         1.         0.9988226  1.         0.99943715
 0.9999995  1.        ]
[0.99999976 1.        ]
[1.]
[0.9995696  0.99999726 1.         1.         0.9999945  1.
 0.88949865 0.99922645 0.9999999  1.         0.8934772  0.8332356
 0.99718946 0.91004026 1.         0.9999993  1.         0.9999995
 0.99962664 0.9714507  0.9957872  0.9999995  1.        ]
[0.9997881  0.99999917 0.99999917 0.99999917 0.9999999  0.99999917
 1.         0.9999988  0.9999988  0.9999999  0.9999615  0.58080256
 0.9978738  0.9999598  1.         0.9999925  0.9999988  0.9999999 ]
[0.9999999  0.95002663]
[0.9999958  0.99999344]
[0.9999403  0.9999969  0.98012793 0.9999994  1.         0.9998733
 1.         1.      

[0.79852414 0.999992  ]
[0.9998679  0.99994767 1.         1.         0.9998361  1.
 0.9835263  0.70335156 1.         1.         1.         1.
 0.9999995  0.99998546 1.         1.         0.5904504  1.
 0.99999547 1.        ]
[0.75826216 0.99999964 0.99994373 0.999863   0.9933977  0.9697148
 0.9992562  0.9986834  0.9999999  0.999992  ]
[0.9997547]
[0.99114484]
[0.985109  0.9999938]
[0.9998173  1.         0.9995403  0.99999964 0.9992582 ]
[0.99999464]
[1.         0.9999994  0.9999994  1.         1.         1.
 0.9999858  1.         1.         1.         0.99822956 0.9866681
 0.9999937  1.         0.9966012  0.99996424 1.         0.99500024
 0.9999993  0.9999355  0.83695185 0.9877556  1.         1.
 1.         0.99999964 1.         1.         1.         1.
 0.9999987  1.         0.99990773 0.99642736 1.         1.
 1.         1.         0.99999905 1.         1.         1.
 0.99999917 0.9999994  0.99990904 0.99999976 1.         0.9999995
 0.9999937  0.99999607 0.7171673  0.9999999  1.     

[1.         0.9999999  0.9995426  0.99999654 0.9999943  1.
 1.         1.         0.99998605 1.         0.9999999  1.
 0.9994592  0.9993223  0.999966   0.9999987  0.9999999  0.9999993
 1.         0.70916826 0.99993753 0.9999871  1.         0.99993026
 0.9999347  0.97700685 0.9999999  1.         0.9999962  1.
 0.9990189  0.99999785 0.99513984 0.9999981  1.         0.99988794
 0.99999917 0.99992275 0.9999999  0.99999857 0.9999939  0.7040047
 0.99999857 1.         0.9041414  0.9999962  0.9999999  0.9999455
 0.99999857 0.99999654 1.         0.9993318  0.9235758  1.
 0.9999987  1.         1.         0.99999964 1.         0.49203575
 0.99999785 1.         1.         0.99999857 1.         0.99903893
 1.         0.9999999  0.99997354 1.         0.9999999  0.954913
 0.99999857 1.         1.         1.         0.9993318  0.99999964
 0.99999964 1.         0.9999883  0.9999999  0.9999987  0.9999939
 0.9999821  1.        ]
[0.99980384 0.9999994  1.         1.         0.99999976 0.7595121
 0.9999993

[0.999876]
[1.]
[0.7775871 0.9999443 0.9999943 1.       ]
[0.9987674  0.9999653  0.79962677 0.53382677 0.9999869  0.99997354
 0.9999995  0.9999999  0.9998462  0.9999987 ]
[1.       0.999819 1.      ]
[0.9999932]
[0.99999964 0.99999905 1.         0.99917275 1.         1.
 0.99999976 0.9999776  0.93998224 0.9999999  1.         1.
 1.         1.         0.9999999  0.9999862  0.99999917 0.99975544
 1.        ]
[0.99997354 1.         0.95687747 0.99999857 1.         0.99998355
 0.99953556 1.         1.         1.         0.8125846  0.99988174
 1.         0.9999999  0.9999981  0.9999995  1.         1.
 0.88944894 0.99999    1.         0.999995   0.54287475 1.
 0.9993808  0.9999969  1.         0.99937516 0.99999714]
[1.         1.         1.         0.9997652  0.9999987  0.99903226
 0.99999976 0.9999995  1.         0.8639096  0.7475912  1.
 0.99947125 0.91163456 0.9994023  0.98324883]
[0.9999659  1.         0.99999857]
[1.]
[0.99999726]
[0.9997379  0.9999844  1.         0.9998248  0.99987435 

[1.         0.53289765 0.9968076  0.99817014 0.9880149  0.99162346]
[1.         0.99999976 0.99999976 0.9999995  0.99999654 1.
 0.99999964 0.99999654 0.99999785 0.9993223  1.         0.9998448
 1.         0.9999999  1.         1.         0.9999999  1.
 0.99962497 1.         0.9999994  0.9999999  1.         1.
 0.9999957  0.99995327 0.9966151  0.99991846 0.99110645 1.
 1.         0.9999999  1.         0.9973828  0.9999858  0.9999999
 0.99997354 0.9999995  0.9999808  0.9999957  1.         0.99999845
 0.9999974  0.99971896 0.52589935 0.9998883  0.9999995  0.9999999
 0.7618163  0.9998462  0.99544597 0.99908006 0.64643425 0.8152127
 0.99999833 1.         1.         0.9993223  0.9999999  0.99992514
 1.         0.99999356 0.99998593 0.9999975  0.53268474 0.9999994
 0.9999814  0.99984896 0.9999902  0.99998677 0.99999976 0.9999758
 1.         0.9999956  1.         0.9999999  0.9999999  0.9999999
 0.99999404 1.         0.9999999  0.9998325  0.9945374  1.        ]
[0.9999995  0.9999981  1.       

[1.]
[0.99999714 0.9999989  0.99643767]
[1. 1.]
[1.         0.9995889  1.         1.         0.95312905]
[0.9932221  0.99999404 0.9999956 ]
[1.]
[0.99995446]
[1.]
[1.         0.998064   0.99999464 1.         0.99999785 0.9950518
 0.9962347  1.         0.9999753  0.9999999  0.9999846  0.9999993
 0.99999964 0.999998   0.9999993  0.99998546 0.6594108  0.9326814
 0.98979586 0.99993956]
[0.9999993  1.         0.9999993  1.         1.         0.99999976
 0.9996469  0.7934618 ]
[1.         0.99999905]
[1.         0.99999297 1.         0.99999905 1.        ]
[0.9990736]
[0.9999999 1.       ]
[0.99891925]
[0.99999547 0.9999999  0.9998871  0.99997425 0.9999914  0.99996793
 1.         0.9999261  1.         0.99983144 0.99998534 0.99999547
 0.99999654 0.9991691  0.99999857 0.99999905 1.         0.9999989
 0.9994592  1.         1.         0.99999976 0.9999883 ]
[1.         1.         1.         0.9999198  0.99999857 1.
 1.         1.         0.9999995  0.9997652 ]
[0.99999976 1.         0.9999999  

[1.]
[0.999961]
[0.99997807]
[0.9999999 1.        0.9999988 0.9999943 1.        0.9785533 0.9993223
 1.       ]
[0.9999999  0.9999999  0.99999595]
[1.         0.99999964 1.         1.         0.9999993  0.99998534
 1.         0.99892634 1.         1.         1.         1.        ]
[1.        1.        1.        0.9999995]
[0.9999914 1.       ]
[0.99999976 0.9599002  0.9999963  0.9999609  1.         1.
 0.9995511 ]
[1.         1.         1.         1.         1.         1.
 1.         1.         1.         0.99999976 0.9999976  0.9999989
 1.         1.         1.         1.         1.         0.9999995
 1.        ]
[0.99999964 0.9905094  0.99999964 0.5049306  0.99999726 0.9999988
 1.        ]
[1.         0.513456   0.9999999  1.         0.9999999  0.9993536
 0.9994916  0.9999999  0.9999999  0.99997866 0.9999999  0.99888545
 1.         1.         0.9999894  0.9456264  0.99995625 0.99994266
 1.         0.9999993  1.         0.77875537 0.9999995  0.99999976
 1.         1.         0.9999999

[0.9999213 0.999969  0.9999924 0.9999993 0.9999639 0.9950193 0.8681901
 0.9999995 1.        0.9999999]
[1.         0.9992912  1.         0.99996984 1.         0.9975932
 0.999887   1.         1.        ]
[1.         0.9999999  0.99992275 1.         0.9999999  0.99999976
 0.9999589  0.57651436 0.99993527 0.9999999  0.99973804 1.
 0.9999982  0.99997354 0.99998546 0.9999999  1.         1.
 1.         0.9999937  1.         0.9999895  1.         0.99999964
 1.         0.9999999  0.99818844 0.5023393  0.9999956  0.9999956
 0.99999964 1.         0.99964786 0.9999902  0.96386206 0.9999999
 0.8360285 ]
[1.         0.9999769  1.         1.         1.         0.9999989
 0.9999385  0.80948937 1.         1.         1.         0.9999707
 1.         0.70538354 0.99987435 0.99986637 0.9999989 ]
[0.9999993  1.         0.9999995  0.99999964 1.         1.
 0.80609155 0.9997781  1.         0.88949865 0.9999964  0.9999416
 0.3974136  1.         0.99999976 1.         0.9999993  0.9999999
 1.         1.     

[0.9999999]
[0.9641532 0.8801424 0.9999999]
[0.9999995  0.9999995  1.         1.         1.         0.9999858
 1.         0.99999    1.         1.         1.         1.
 1.         1.         1.         0.9999999  1.         0.9996008
 0.9989693  0.9999976  0.99990904 1.         1.         1.
 0.9999831  0.99996054 1.         1.         0.9887136  0.9999999
 0.9874271  0.99679863 0.9995864  1.        ]
[0.9902265  0.9990651  0.98871964]
[0.75312626 0.5904504  0.99999976 0.9999411  0.99998975 0.9999354
 0.97995317 0.9999999  0.9999993  0.9999341  0.9999999  1.
 0.99887425 0.99973804 0.97715545 0.9999958  1.         0.977367
 1.         0.9999999  0.9999987  1.         1.         1.
 0.999992   0.9701653  0.90057313 0.9999982  0.9941467  0.99999857
 0.8380473  0.9999505  0.9999999  0.99999964 0.9999999  0.9999999
 0.9999999  0.9999969  0.99998045 0.9993223  0.99999464 0.9999993
 0.9999982  0.9997831  0.9999821  0.9660342  0.99773824 0.9999999
 0.9999995  1.         1.         0.81462634 

[0.9991072 0.9999995]
[0.99999976 0.99999785]
[0.99999547]
[1.]
[0.9884113  0.99999356 0.5904504  1.         1.         1.
 1.         0.5904504  0.99999964 1.         1.         1.
 0.99999976 0.9999999  1.         1.         0.99999785 0.9999968
 0.9397992  0.9999989  1.         1.         0.99999976 0.9999995
 0.99844474 0.999998   0.99999976 0.99983513 0.9741933  1.
 1.         0.9978313  0.99999964 0.99999964 0.99999964 0.99999964
 0.99948406 0.9738429  1.         0.9916257  1.         0.9999999
 1.         0.99999833 1.         0.9916257  1.        ]
[1.         0.9997662  0.9999583  0.9999999  1.         0.9999924
 0.9999975  1.         0.9999995  0.99997354 1.         0.9999994
 1.         0.9999914  0.99999976 0.9999808  1.         1.
 0.99983335 0.99998915 0.9999646  0.9999987  0.6134737  0.9999999
 1.         0.99997354 1.         0.9996375  0.9999976  1.
 0.99999964 1.         1.         1.         0.9999999  0.9999918
 0.99999654 1.         1.         1.         1.        

[1.         1.         0.99999595 0.9999995  0.999974  ]
[1.         1.         0.99997354 0.9999999  0.9998104  0.99884593
 0.9877615  1.        ]
[1.]
[0.9999795]
[0.99999976]
[0.9998068  0.9904118  1.         0.7937107  1.         1.
 0.9999505  0.9999819  0.9999037  0.99991226 1.         1.
 0.9999995  1.         0.9999987  0.92524135 1.        ]
[0.9999994  0.99999976 0.9990464  0.9998393 ]
[0.99999964 0.99778557 1.         0.9994992  1.         0.9997516
 0.99999785 0.99999785 1.         0.9992073  0.9999999  0.74286646
 0.9999871  1.         0.9412526  1.         1.         0.9999999
 0.99952114 0.9999684  0.9999999  1.         1.         1.
 0.99999654 0.96824    0.99972373 0.94581467 0.94194984 1.        ]
[0.9707053 0.9999987 0.9980039]
[0.99999905 0.99999976 1.         1.         0.9962691  1.
 1.        ]
[0.9999999 1.        0.9999999 0.9981013 0.9999988 0.9999999]
[0.99999964 1.         0.99916124 0.9999902 ]
[0.8051403]
[0.9999839  0.99999726 0.99999845]
[0.9999968]
[1.]

[0.9999999  1.         0.9999995  1.         1.         1.
 1.         0.9999964  0.5923292  1.         1.         0.99997354]
[0.96711916 0.9985606  0.9999175  1.        ]
[0.99999833 1.         1.         0.99167985 1.         1.        ]
[0.99973875 1.        ]
[0.99999535]
[1.         0.9999969  0.9997811  0.9999747  1.         0.99998057
 0.9999937  1.         0.9071333  0.9999696  0.99994147 0.96255356
 0.9995722  0.9999989  1.         0.9999976  0.9999999  0.9996412
 0.9999999  0.983639   0.9999999  0.99975437 0.9999498  0.99999475
 0.9999957 ]
[1.         0.99999976 1.         0.9976876  1.        ]
[1.]
[0.9920054  0.99999964 1.         0.8702301  0.99999905 0.99994946
 1.         1.         0.99997187 0.9995931  0.9999994  0.9481202 ]
[0.9788037 1.       ]
[0.99999726 0.98474705]
[0.99748224 1.         0.9999995 ]
[0.8681901 1.       ]
[0.9999931 0.9999999]
[0.99999785 0.99986434 1.         0.99905115 1.         0.99999785]
[0.9999925]
[0.923591]
[0.9677335 0.9999999 1.      

[0.9998661  0.99835014 0.9999937 ]
[1.]
[0.99999964]
[0.9999939]
[0.92187816]
[0.999938  0.9999993]
[0.99999964 1.         0.99999285 1.         0.99980015 1.
 0.99997926 0.9999999 ]
[0.995475   0.9996722  0.9999999  0.9955745  0.99999714 0.99999976]
[0.9999981  1.         0.99989927 1.        ]
[1.         0.7773375  0.99870956]
[0.9999993]
[0.93154246 0.9738748 ]
[1.         0.9999976  0.9999999  0.98892874 0.9999995  0.9995888
 0.99997354 0.9999999  0.9999994  0.99997354 0.9999759  0.9997824
 0.51050436 0.99997354 0.99999964 1.         0.99997354]
[1.         1.         1.         0.82595795]
[1.         0.9999995  0.9999995  1.         0.99999964 0.7689074
 0.99999595 1.        ]
[1.        0.9999999 0.9999863 1.       ]
[0.9970216  0.99999905]
[0.99973017]
[0.999925]
[0.99999976 0.9993223  0.99999654 1.         1.         0.9999999 ]
[0.9999962]
[0.99997485 0.9908014  0.9999304  0.9999726  1.        ]
[0.9999993 0.9998779 0.9999999 0.9999999 1.       ]
[0.99973816]
[1.]
[0.9999474

[0.9867975]
[0.96885264]
[0.99970055]
[0.99996936 1.         0.99999905 1.         1.        ]
[0.99997354]
[1.]
[1.]
[0.9999999]
[0.99997723 0.9998325  0.99999976 0.99913836 1.         0.9994734
 0.99996066 0.9997173 ]
[0.5904504 0.9999999]
[0.99998426]
[0.9998579  0.69005543 0.9998242 ]
[1.]
[0.99999976]
[1.]
[0.99994147 1.         0.9999999  0.9999994  0.71829337 0.9999982
 1.         0.99983335 1.         1.         1.         0.9999999
 0.9996232  0.63784593 1.         0.9993223  0.99999964 1.        ]
[0.60437196 0.9998053  0.9999131  0.99315274 0.999688  ]
[0.9979887 1.        1.        1.        1.       ]
[1.]
[0.9999478]
[1.]
[1.         0.9999682  0.9942316  0.9999995  1.         1.
 1.         0.99999964]
[0.99997354 0.99999857 0.9999995  0.9999999  1.         0.9999956
 0.99663144 1.         0.9999995  0.9999969  0.8486999  1.
 0.98550165 0.99995244 0.99999547 0.9998909 ]
[0.9999795]
[0.99999726 0.9999969  1.         1.         0.5197665  0.91887045
 1.         1.         

[1.         0.9999914  0.9997379  0.99970824 0.9999304 ]
[1.         0.99999964 0.9999969  1.         1.         0.9790901 ]
[1.]
[0.99999213 0.9999809 ]
[0.99999774 0.8275521  0.99999964]
[0.99999595 0.9993315  0.9999088 ]
[0.99999845]
[1.         0.998689   0.9999994  0.9997875  0.99984264 1.        ]
[0.99993086 0.9999895  0.9995511 ]
[0.99991465 0.99999106]
[0.9993672  0.99998236]
[0.9996511  1.         0.99206924]
[0.9999937 0.9999647]
[0.9997379  0.99941325 0.99999404 1.         1.        ]
[0.99998283]
[0.99999857 0.99999905]
[1.]
[0.9998325 0.9999999 0.9998325]
[0.99849355 0.99999964 1.        ]
[1.         0.99795866 0.9999981  0.999129   0.99999785 0.99991155
 0.99999    1.         0.99999964 0.999998   0.9999924  1.        ]
[0.5501158 0.9999995 0.9999999 0.8196577 1.        1.        1.
 1.       ]
[0.999998  0.9999863]
[0.9999945 1.       ]
[1.         0.89007425]
[0.9999999]
[0.9999999 1.       ]
[0.9999616  0.99970645 1.        ]
[0.99999714]
[0.99991584 0.99999964 0.999

[1.         1.         1.         1.         1.         1.
 1.         1.         1.         0.9999999  0.99997354 0.9993113
 0.9979876  1.        ]
[0.9999999 0.9999639]
[0.99999976 1.         1.         0.99960333 0.9996375  0.99999976
 0.99999785 0.99999774 0.99999857 0.9979961  0.99998677 0.9999969
 0.9999999  0.9999999  0.99998724 0.9993223  1.         0.9999999
 0.99999726 1.         0.99999976 1.        ]
[0.9999999 1.       ]
[1.         1.         0.99999666 1.         0.999881   1.
 1.         1.         0.9998078  1.        ]
[0.9998907]
[0.99899]
[0.8771572]
[1.        0.9999734 0.9750329]
[0.9999429]
[0.99609524]
[1.]
[1.]
[0.9956398]
[0.9999982  0.9999877  1.         0.99999785 1.         0.9999838
 0.99999654 1.         0.999966   0.85464    0.99999654 0.9999969
 1.         0.99998724 0.9999864  0.9999958  0.9999999  0.99999976
 1.         0.9999958  0.99999976 1.         0.9999999  1.
 1.         1.         1.         1.         1.         1.
 0.99999976 0.9999932  0.99

/home/dbabenko/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/dbabenko/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
for topic in google_topic_sent_reports:
    print("TOPIC: ", topic)
    print(v)

TOPIC:  Location
              precision    recall  f1-score   support

         neg       0.25      0.57      0.35         7
        neut       0.00      0.00      0.00        43
         pos       0.88      0.98      0.93       311

    accuracy                           0.85       361
   macro avg       0.38      0.52      0.42       361
weighted avg       0.76      0.85      0.81       361

TOPIC:  Kitchen
              precision    recall  f1-score   support

         neg       0.23      0.55      0.32        49
        neut       0.00      0.00      0.00        74
         pos       0.56      0.57      0.56       121

    accuracy                           0.39       244
   macro avg       0.26      0.37      0.29       244
weighted avg       0.32      0.39      0.34       244

TOPIC:  Service
              precision    recall  f1-score   support

         neg       0.30      0.75      0.43        12
        neut       0.00      0.00      0.00        22
         pos       0.94   

In [34]:
google_topic_sent_reports[topic]

'              precision    recall  f1-score   support\n\n         neg       0.19      1.00      0.32        10\n        neut       0.00      0.00      0.00        42\n         pos       0.22      0.22      0.22        18\n\n    accuracy                           0.20        70\n   macro avg       0.14      0.41      0.18        70\nweighted avg       0.08      0.20      0.10        70\n'

# Demo result

#### select the same hotel for google and booking reviews

In [84]:
random_idx = np.random.choice(range(len(google_booking_hotels)))
selected_goole_hotel = list(google_booking_hotels.keys())[random_idx]
assert selected_goole_hotel in google_hotel_reviews
selected_goole_hotel

'Міні-готель SkyHome'

## Analyze from google reviews

In [85]:
selected_goole_hotel

'Міні-готель SkyHome'

In [86]:
%%time
hotel_collocations = collocation_extractor.extract_for_texts(google_hotel_reviews[selected_goole_hotel]['texts'])

CPU times: user 3.68 s, sys: 15.7 ms, total: 3.7 s
Wall time: 3.7 s


In [87]:
visible_collocations = [Utils.generate_text_from_collocation(collocation) for collocation in hotel_collocations]
visible_collocations

['відмінний готель',
 'сучасний ремонт',
 'загальний холодильник і бойлер',
 'дружелюбний персонал',
 'чудовий нічний вид з окна',
 'осталісь задоволені',
 'увечері шикарний вид з вікна',
 'маленькі кімнати з видом на балкон',
 'чудовий номер та умови проживання',
 'також окремої уваги заслуговує',
 'відмінне ставлення персоналу',
 'щирий прийом',
 'хороший відпочинок',
 'чудове місце для ночівлі',
 'інтимна обстановка',
 'хороший готель на околиці києва',
 'приємний адміністратор',
 'було більше посуди',
 'домашня атмосфера',
 'в стінах електричний гул',
 'персонал відкриває',
 'короче сервісом і не пахло',
 'відмінний сервіс',
 'привітний персонал',
 'демократичні ціни',
 'хороший персонал',
 'непоганий готельчик',
 'відмінний сервіс',
 'хороший міні',
 'міні готель',
 'прийнятними цінами',
 'ліжко стукала',
 'гарне місце для зупинки']

#### Classify topic of each collocation

In [88]:
visible_topic_collocations, topic_collocations = topic_classifier.predict(hotel_collocations)
visible_topic_collocations

{'Property': [('відмінний готель', 1.0),
  ('сучасний ремонт', 1.0),
  ('хороший відпочинок', 0.3),
  ('в стінах електричний гул', 1.0),
  ('демократичні ціни', 1.0),
  ('непоганий готельчик', 1.0),
  ('хороший міні', 0.7),
  ('міні готель', 1.0),
  ('прийнятними цінами', 1.0)],
 'Kitchen': [('загальний холодильник і бойлер', 1.0),
  ('було більше посуди', 0.7)],
 'Service': [('дружелюбний персонал', 1.0),
  ('осталісь задоволені', 0.75),
  ('чудовий номер та умови проживання', 0.5),
  ('також окремої уваги заслуговує', 0.9),
  ('відмінне ставлення персоналу', 0.85),
  ('щирий прийом', 0.9),
  ('приємний адміністратор', 1.0),
  ('персонал відкриває', 1.0),
  ('короче сервісом і не пахло', 1.0),
  ('відмінний сервіс', 1.0),
  ('привітний персонал', 1.0),
  ('хороший персонал', 1.0),
  ('відмінний сервіс', 1.0)],
 'Room amenities': [('чудовий нічний вид з окна', 1.0),
  ('увечері шикарний вид з вікна', 1.0),
  ('маленькі кімнати з видом на балкон', 0.9)],
 'Location': [('чудове місце для

In [89]:
 topic_collocations_sent, topic_summary = Utils.define_sentiments_and_summary(topic_collocations,
                                                                        visible_topic_collocations,
                                                                        collocation_sent_classifier, 
                                                                        topic_classifier,
                                                                       2)

In [90]:
topic_collocations_sent

{'Property': [('відмінний готель', 1.0, 'pos'),
  ('сучасний ремонт', 1.0, 'pos'),
  ('хороший відпочинок', 0.3, 'pos'),
  ('в стінах електричний гул', 1.0, 'neut'),
  ('демократичні ціни', 1.0, 'pos'),
  ('непоганий готельчик', 1.0, 'pos'),
  ('хороший міні', 0.7, 'pos'),
  ('міні готель', 1.0, 'neut'),
  ('прийнятними цінами', 1.0, 'pos')],
 'Kitchen': [('загальний холодильник і бойлер', 1.0, 'neut'),
  ('було більше посуди', 0.7, 'neut')],
 'Service': [('дружелюбний персонал', 1.0, 'pos'),
  ('осталісь задоволені', 0.75, 'pos'),
  ('чудовий номер та умови проживання', 0.5, 'pos'),
  ('також окремої уваги заслуговує', 0.9, 'neut'),
  ('відмінне ставлення персоналу', 0.85, 'pos'),
  ('щирий прийом', 0.9, 'pos'),
  ('приємний адміністратор', 1.0, 'pos'),
  ('персонал відкриває', 1.0, 'neut'),
  ('короче сервісом і не пахло', 1.0, 'neut'),
  ('відмінний сервіс', 1.0, 'pos'),
  ('привітний персонал', 1.0, 'pos'),
  ('хороший персонал', 1.0, 'pos'),
  ('відмінний сервіс', 1.0, 'pos')],
 '

In [91]:
Utils.print_hotel_summary(topic_summary, detailed=False)

	+ непоганий готельчик
	+ прийнятними цінами
	 загальний холодильник і бойлер
	 було більше посуди
	+ приємний адміністратор
	+ дружелюбний персонал
	 увечері шикарний вид з вікна
	 маленькі кімнати з видом на балкон
	+ чудове місце для ночівлі
	+ гарне місце для зупинки
	 інтимна обстановка
	 ліжко стукала


In [92]:
Utils.print_hotel_summary(topic_summary, detailed=True)


#######################################
TOPIC:  Property
SENTIMENT:  pos
	+ непоганий готельчик
	+ прийнятними цінами

#######################################
TOPIC:  Kitchen
SENTIMENT:  neut
	 загальний холодильник і бойлер
	 було більше посуди

#######################################
TOPIC:  Service
SENTIMENT:  pos
	+ приємний адміністратор
	+ дружелюбний персонал

#######################################
TOPIC:  Room amenities
SENTIMENT:  neut
	 увечері шикарний вид з вікна
	 маленькі кімнати з видом на балкон

#######################################
TOPIC:  Location
SENTIMENT:  pos
	+ чудове місце для ночівлі
	+ гарне місце для зупинки

#######################################
TOPIC:  Atmosphere
SENTIMENT:  neut
	 інтимна обстановка

#######################################
TOPIC:  Sleep
SENTIMENT:  neut
	 ліжко стукала


## Analyze from booking reviews

In [93]:
booking_hotel = google_booking_hotels[selected_goole_hotel]

In [94]:
booking_hotel_texts = Utils.get_booking_review_texts(booking_hotel_reviews, booking_hotel)

In [95]:
%%time
booking_collocations = collocation_extractor.extract_for_texts(booking_hotel_texts)

CPU times: user 39.7 s, sys: 201 ms, total: 39.9 s
Wall time: 39.9 s


In [96]:
booking_visible_collocations = [Utils.generate_text_from_collocation(collocation) for collocation in booking_collocations]
booking_visible_collocations

['персонал приємний',
 'персонал приємний',
 'зручним розташування готелю',
 'номер дуже маленький',
 'спальному ліжку',
 'ванній кімнаті',
 'душова кабіна була брудна',
 'не зрозуміла політика зміни',
 "сподобався інтер'єр",
 "сподобався інтер'єр",
 'має стоянки для авто',
 'не працювала лампа',
 'була напівтемрява',
 'хороший ремонт та меблі',
 'готель розташований',
 'останніх поверхах',
 'останній поверх ліфтом',
 'ціна доступна',
 'з спокоєм не було',
 'хороша адміністратор',
 'чарівна та приємна пані',
 'гарна панорама',
 'гарна панорама відкрилась',
 'поблизу є платна стоянка',
 'чути сусідів',
 'навіть коли ведуть звичайну розмову',
 'дуже тонкі стіни',
 'готель розміщений кухонний куток',
 'є можливість',
 'чай безкоштовний',
 'пральною машиною та холодильником',
 'постійно ведеться відеонагляд',
 'є кондиціонер',
 'ведеться будова',
 'постійний гуркіт техніки і стукіт',
 'рецепція знаходиться',
 'сусідньому під‘їзді',
 'другому під‘їзді',
 'готель розмістився',
 'фотографії н

In [97]:
booking_visible_topic_collocations, booking_topic_collocations = topic_classifier.predict(booking_collocations)
booking_visible_topic_collocations

{'Service': [('персонал приємний', 1.0),
  ('персонал приємний', 1.0),
  ('не зрозуміла політика зміни', 0.55),
  ('з спокоєм не було', 0.35),
  ('хороша адміністратор', 1.0),
  ('чарівна та приємна пані', 0.95),
  ('чути сусідів', 0.85),
  ('навіть коли ведуть звичайну розмову', 0.55),
  ('рецепція знаходиться', 1.0),
  ("обов'язковому порядку", 0.7),
  ('оплата тільки готівкою+ беруть завдаток', 0.6),
  ('ввічливий персонал', 1.0),
  ('нормальному розумінні', 0.95),
  ('привітний персонал', 1.0),
  ('прекрасне відношення персоналу', 0.95),
  ('прекрасне відношення персоналу', 0.95),
  ('приємно здивувало співвідношення', 0.55),
  ('адміністратор зажадала', 1.0),
  ('сплачуючи комісію банку', 0.7),
  ('персонал швидко відреагував', 1.0),
  ('персонал швидко відреагував', 1.0),
  ('безсовісний адміністратори', 1.0),
  ('адміністратор не прийшла', 1.0),
  ('адміністратор погодилася', 1.0),
  ('адміністратор і каже', 1.0),
  ('сплатити заставу', 0.95),
  ('враження неоднозначні', 0.6),
 

In [98]:
booking_topic_collocations_sent, booking_topic_summary = Utils.define_sentiments_and_summary(booking_topic_collocations,
                                                                                       booking_visible_topic_collocations,
                                                                                       collocation_sent_classifier, 
                                                                                        topic_classifier,
                                                                                       2)

In [99]:
#booking_topic_collocations_sent

In [101]:
Utils.print_hotel_summary(booking_topic_summary, detailed=False)

	+ дуже привітно і чудовий адміністратор
	+ дуже привітно і чудовий адміністратор
	 поставили додаткове місце
	 місце зовсім не в центрі
	 пройти ряд коридорів від ліфта
	 саме там розташовані номери
	 дуже погана звукоізоляція
	 дуже погана звукоізоляція
	 вранці) гарячої води просто не застав
	 дуже погано працювала каналізація
	 поблизу є платна стоянка
	 має стоянки для авто
	 открывается вид на місто
	 тому вид з вікна на кам
	 мансардним поверсі
	 останніх поверхах
	 фото відповідають дійсності
	 фото відповідають дійсності
	 готель розміщений кухонний куток
	 так же холодильник
	 загальна кухня
	 фотографії не відповідають реальності
	 термінал не працював
	 загальній культурі населення
	 кухонними зоною
	 розрахувати ся
	 зробленим вибором на користь
	 немає можливості перекладу
	+ прибирання не повинна


### Generated text summary about hotel 

In [ ]:
#TODO:

In [83]:
#TODO: